template_path: kms/cross-account-kms.yaml

parameters:
  AllowedPrincipalsForAdmin: 
    - "0987654321" ## <PASS DR ACCOUNT ID HERE>
    - "arn:aws:iam::0987654321:role/example_rolename"  ## <PASS LIST OF IAM ROLE ARNS THAT WILL BE THE ADMINISTRATORS OF THE KEY>
  AllowedPrincipalsForKeyUsage:
   - "0987654321" ## <OPTIONAL TO PASS DR ACCOUNT ID HERE IN ORDER TO LET THE DR ACCOUNT TO USE THE KEY>
   - "arn:aws:iam::0987654321:role/example_rolename"  ## <PASS LIST OF IAM ROLE ARNS THAT WILL BE THE ADMINISTRATORS OF THE KEY>
   - "arn:aws:iam::0987654321:user/provisioning_user" ## <ARN of the IAM USER OR ROLE WHO IS PROVISONING THIS KEY, THIS IS TO AVOID CLOUDFORMATION THROWING THIS ERROR "Resource handler returned message: "The new key policy will not allow you to update the key policy in the future."">
  AllowedPrincipalsForGrants: "arn:aws:iam::0987654321:role/example_rolename,0987654321"  ## <PASS COMMA SEPERATED LIST OF PRINCIPALS (IAM ROLE ARNS OR ACCOUNT ID) THAT WILL BE THE ADMINISTRATORS OF THE KEY AS WELL AS IF ANY IAM ARNS FROM THE DESTINATION ACCOUNT OR THE DESTINATION ACCOUNT ID>
  DisplayName: DR-Prod-RDSCustomerKey
  ParentSNSStack: !stack_output drprod/sns/snstopics.yaml::StackName