template_path: rds-snapshot-automation/snapshot_tool_rds_dest_copy.yaml.j2

hooks:
  before_create:
    - !sceptre_s3_upload lambda_code/copy_snapshots_dest_rds
  before_update:
    - !sceptre_s3_upload lambda_code/copy_snapshots_dest_rds

parameters:
  Platform: exampleApp        ## <PASS APPLICATION NAME HERE TO PROVISION APPLICAITON BASED RESOURCES >
  SnapshotPattern: "prod"    ## <PASS NAME OF THE SHARED SNAPSHOT AS A REGULAR EXPRESSION TO TARGET THE AVAILABLE SNAPSHOTS TO BE COPIED. IN MOST CASES, A SIMPLE NAME LIKE 'prod', 'dev', 'uat' or ANY ENVIRONMENT NAMES LIKE THESE WILL SUFFICE>
  KmsKeyDestination:
    !stack_output "drprod/kms/cross-account-key.yaml::KeyArn"
  KmsKeySource: "arn:aws:kms:ap-southeast-2:0987654321:key/f72cff19-9416-4886-8a32-a1381186a42a"  ## <PASS THE ARN OF THE SOURCE ACCOUNT KMS KEY (CREATED EITHER VIA ../../prod/kms/cross-account-kms.yaml OR AN ALREADY EXITING KEY)>
  CopySchedule: '100'
  CopyRetentionDays: '1'
  LogLevel: 'INFO'
  ParentSNSStack:
    !stack_output "drprod/sns/snstopics.yaml::StackName"

sceptre_user_data:
  Code:
    S3Bucket: !stack_output "drprod/s3/sceptre-function-code-bucket.yaml::BucketName"
    S3Key: !sceptre_s3_key lambda_code/copy_snapshots_dest_rds